/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'MarkPerry' at '12/12/13 10:02 AM' with Gradle 1.9
 *
 * @author MarkPerry, @date 12/12/13 10:02 AM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
