/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'MarkPerry' at '12/12/13 10:02 AM' with Gradle 1.9
 *
 * @author MarkPerry, @date 12/12/13 10:02 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
